name: Matrix Demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix: # run same job with diff configurations
            # eg: build app on different envts or testing in different OS
                node-version: [12, 14, 16]
                operating-system: [ubuntu-latest, windows-latest]
                include: # allows to add standalone combinations even add new combinations
                    - node-version: 18
                      operating-system: ubuntu-latest
                exclude: # excule a particluar combination
                    - node-version: 12
                      operating-system: windows-latest
        runs-on: ${{matrix.operating-system}} # values can be picked dynamically from the matrixß
        steps:
            - name: Get Code
              uses: actions/checkout@v3
            - name: Install Node JS
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-version}}
            - name: Install Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
            
